<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "socialcms"
 *
 * Auto generated by Extension Builder 2014-09-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SocialCMS',
	'description' => 'An activitystrea.ms implementation for TYPO3',
	'category' => 'plugin',
	'author' => 'Cedric Ziel',
	'author_email' => 'cedric@cedric-ziel.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);